- name: Add jump user
  ansible.builtin.user:
    name: jump
    shell: "/bin/bash"

- name: Add pubkeys to jump
  ansible.posix.authorized_key:
    user: jump
    key: "{{ lookup('file', 'user_keys.pub') }}"
    exclusive: True


# sshd config Include is a shitshow. Therefore we have to add the include file + replace some parameters
# otherwise it would not work.
- name: Create jump_sshd config
  template:
    src: 'sshd_config_jump.j2'
    dest: "/etc/ssh/sshd_config.d/jump.conf"
    mode: '0600'
    owner: 'root'
    group: 'root'
    validate: '/usr/sbin/sshd -T -C user=root -C host=localhost -C addr=localhost -C lport=22 -f %s'
  notify: restart sshd

- name: Replace AllowUsers
  lineinfile:
    path: "/etc/ssh/sshd_config"
    regex: "^(#)?{{item.key}}"
    line: "{{item.key}} {{item.value}}"
    state: present
  loop:
    - { key: "AllowUsers", value: "AllowUsers redan jump" }  # Allows users redan and jump to connect from everywhere.
  notify:
    - restart sshd
