- name: Install msmtp
  ansible.builtin.apt:
    pkg:
    - msmtp
    - msmtp-mta
    - mailutils
    - bsd-mailx
    state: present

- name: Copy msmtp config
  template:
    src: 'msmtp.conf.j2'
    dest: "/etc/msmtprc"
    mode: '0644'
    owner: 'root'
    group: 'root'

- name: Copy aliases config
  ansible.builtin.copy:
    src: mailconf/aliases
    dest: /etc/aliases
    owner: root
    group: root
    mode: '0644'


- name: Create a symbolic link for sendmail
  ansible.builtin.file:
    src: /usr/bin/msmtp
    dest: /usr/sbin/sendmail
    owner: root
    group: root
    state: link
