- name: Add Proxmox GPG key
  ansible.builtin.get_url:
    url: https://enterprise.proxmox.com/debian/proxmox-release-bullseye.gpg
    dest: /etc/apt/trusted.gpg.d/proxmox-release-bullseye.gpg

- name: Add proxmox1 repository into sources list
  ansible.builtin.apt_repository:
    repo: deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription
    state: present

- name: Add ceph repository into sources list
  ansible.builtin.apt_repository:
    repo: deb http://download.proxmox.com/debian/ceph-pacific bullseye main
    state: present

- name: Remove existing firmware packages
  ansible.builtin.apt:
    pkg:
    - firmware-bnx2x
    - firmware-realtek
    - firmware-linux-free
    purge: true
    state: absent

- name: Install proxmox
  ansible.builtin.apt:
    pkg:
    - postfix
    - open-iscsi
    - proxmox-ve
    state: present

- name: Delete enterprise sources.list
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    state: absent