# How to generate a password hash?
# https://stackoverflow.com/a/17992126
# Password is saved in bitwarden.redan.ch.

- name: Set root password
  ansible.builtin.user:
    name: root
    update_password: always
    password: "$6$rounds=656000$saD3yy53x8ZFvZXu$CTaubsr0ekP4Tk6ifwL90/XsjQ7r11LqLJYB0rpojosi14yZMqCsRSARpQPDRIWg1299g6gvj0yDQvTuOFlTW0"


