- name: Allow ssh
  community.general.ufw:
      rule: allow
      name: OpenSSH
  when: ansible_distribution == 'Ubuntu'

- name: enable UFW
  community.general.ufw:
    state: enabled
  when: ansible_distribution == 'Ubuntu'

